name: Run Minecraft AFK Bot

on:
  workflow_dispatch:
    inputs:
      bot_username:
        description: 'Username Akun Minecraft'
        required: true
        default: 'Solaris'
      bot_password:
        description: 'Password Akun Minecraft'
        required: true
        default: 'memek#1'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: node fishing.js "${{ github.event.inputs.bot_username }}" "${{ github.event.inputs.bot_password }}"
